# Generated by Django 5.1.1 on 2024-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='predicted_resolution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='recommended_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
